<h1>Add a blog post</h1>

<?php
$form = $this->form;
$form->setAttribute("action", $this->url());

$fieldset = $form->get("post");

$title = $fieldset->get("title");
$title->setAttribute("class", "form-control");


$text = $fieldset->get("text");
$text->setAttribute("class", "form-control");


$submit = $form->get("submit");
$submit->setAttribute("class", "btn btn-primary");

$form->prepare();

echo $this->form()->openTag($form);
?>

<fieldset>
    <div class="form-group">
        <?php echo $this->formLabel($title); ?>
        <?php echo $this->formElement($title); ?>
        <?php echo $this->formElementErrors()->render($title, ["class" => "help-block"]) ?>
    </div>

    <div class="form-group">
        <?php echo $this->formLabel($text); ?>
        <?php echo $this->formElement($text); ?>
        <?php echo $this->formElementErrors()->render($text, ["class" => "help-block"]) ?>
    </div>
</fieldset>

<?php

echo $this->formSubmit($submit);
echo $this->form()->closeTag();