<?php
  $loopCounter = $this->partialLoop()->getPartialCounter();
?>

<div class="carousel-item align-horizontal <?php echo ($loopCounter === 1)  ? "active" : null; ?> ">
    <div class="row">
        <div class="col-md-3 offset-md-2 my-auto pb-5">
            <img src="<?php echo $this->imgPath; ?>" class="img-fluid">
        </div>
        <div class="col-md-5 col-sm-3 text-md-start text-lg-start text-center my-auto mx-5">
            <div class="row">
                <p class="boldFont sectionHeading col-10 col-md-12 col-lg-12"><?php echo $this->heading; ?></p>
            </div>
            <p class="section-content col-10 col-md-12 col-lg-12"><?php echo $this->text; ?></p>
        </div>
    </div>
</div>