<div class="container-fluid">
    <div class="container">
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner text-center">
                <?php
                echo $this->partialLoop(
                    "/partial/items.phtml",
                    [
                        [
                            "imgPath" => "/img/snug-energy.png",
                            "heading" => "What Rebecca from Snug Energy had to say...",
                            "text" => "The service has been great when we have used it, one of our customers the other day actually got his money within a couple of hours.",
                        ],
                        [
                            "imgPath" => "/img/mb-gas-heating.png",
                            "heading" => "MB Gas & Heating",
                            "text" => "Customer has already contacted me and paid in full, so I’m in the understanding the process has been very straight-forward.",
                        ],
                        [
                            "imgPath" => "/img/mb-gas-heating.png",
                            "heading" => "What Sean from Doors Direct had to say...",
                            "text" => "We are pleased and happy with the process and it’s very easy to navigate through.",
                        ],
                        [
                            "imgPath" => "/img/doors-direct.png",
                            "heading" => "What Mr Maher from S & S Windows had to say...",
                            "text" => "Very easy to use. First class service, excellent throughout, made very simple and very professional. Can’t fault it at all, it’s such a well-run process.",
                        ],
                        [
                            "imgPath" => "/img/sns-windows.png",
                            "heading" => "What David from Mills Medical had to say...",
                            "text" => "Ideal4finance are great to work with, always responsive and helpful with any queries we have. We like the flexibility of the loans, with successful applications for our clients from a variety of backgrounds, and sometimes where they have failed to get a loan elsewhere. We also like the portal where we can track everything.",
                        ],
                        [
                            "imgPath" => "/img/mills-medical.png",
                            "heading" => "Enhance Me Training Academy",
                            "text" => "Really good, really happy with the service so far. We’ve had a lot more people getting accepted going through Ideal4Finance than with our previous provider.",
                        ],
                        [
                            "imgPath" => "/img/enhance-me.png",
                            "heading" => "Enhance Me Training Academy",
                            "text" => "The service is really good, with regular updates on our customers’ applications. When we send a customer over, we appreciate that they are looked after and dealt with by Ideal4Finance without hassle. Some customers get the funds the same day which is great. We feel protected as a business working with Ideal4finance, due to their process, which gives us peace of mind.",
                        ],
                        [
                            "imgPath" => "/img/basi.png",
                            "heading" => "What Gareth from Basi Home Improvements had to say...",
                            "text" => "I am very happy with the facility and service. Ideal4finance offers support to people who can’t afford the money up front, giving them options on how to spread the cost, and help better themselves for the future.",
                        ],
                        [
                            "imgPath" => "/img/cosmetic-couture.png",
                            "heading" => "What Sharon from Cosmetic Couture had to say...",
                            "text" => "I am very happy with the facility and service, Ideal4finance offers support to people who can’t afford the money up front and gives more options on how to spread the costs and help better themselves for the future!",
                        ],
                    ]
                );
                ?>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                    data-bs-slide="prev">
                <span aria-hidden="true" class="fa fa-chevron-left fa-5x blackFont"></span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                    data-bs-slide="next">
                <span aria-hidden="true" class="fa fa-chevron-right fa-5x blackFont"></span>
            </button>
        </div>
    </div>
</div>