<?php

$title = "Players";
$this->headTitle($title);
?>

<h1><?php
    echo $this->escapeHtml($title); ?></h1>s
<p>
    <a href="<?php
    echo $this->url("add", ["action" => "add"]); ?>">Add new Player</a>
</p>
<!---->
<!--<table class="table">-->
<!--    <tr>-->
<!--        <th>First Name</th>-->
<!--        <th>Last Name</th>-->
<!--        <th>&nbsp;</th>-->
<!--    </tr>-->
<!--    --><?php
//    foreach ($players as $player) : ?>
<!--        <tr>-->
<!--            <td>--><?php
//                echo $this->first_name; ?><!--</td>-->
<!--            <td>--><?php
//                echo $this->last_name; ?><!--</td>-->
<!--            <td>-->
<!--                <a href="--><?php
//                echo $this->url("players", ["action" => "edit", "id", $player->id]) ?><!--">Edit</a>-->
<!--                <a href="--><?php
//                echo $this->url("players", ["action" => "delete", "id", $player->id]) ?><!--">Delete</a>-->
<!--            </td>-->
<!--        </tr>-->
<!--    --><?php
//    endforeach; ?>
<!--</table>-->